<a href="https://colab.research.google.com/github/NadaMagdy-hub/Olist-E-Commerce-Data-Analysis/blob/main/customers.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import re

In [ ]:
customers = pd.read_csv("olist_customers_dataset.csv")

In [ ]:
customers.head()

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP

In [ ]:
customers.tail()

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
99436,17ddf5dd5d51696bb3d7c6291687be6f,1a29b476fee25c95fbafc67c5ac95cf8,3937,sao paulo,SP
99437,e7b71a9017aa05c9a7fd292d714858e8,d52a67c98be1cf6a5c84435bd38d095d,6764,taboao da serra,SP
99438,5e28dfe12db7fb50a4b2f691faecea5e,e9f50caf99f032f0bf3c55141f019d99,60115,fortaleza,CE
99439,56b18e2166679b8a959d72dd06da27f9,73c2643a0a458b49f58cea58833b192e,92120,canoas,RS
99440,274fa6071e5e17fe303b9748641082c8,84732c5050c01db9b23e19ba39899398,6703,cotia,SP

In [ ]:
customers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 5 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   customer_id               99441 non-null  object
 1   customer_unique_id        99441 non-null  object
 2   customer_zip_code_prefix  99441 non-null  int64
 3   customer_city             99441 non-null  object
 4   customer_state            99441 non-null  object
dtypes: int64(1), object(4)
memory usage: 3.8+ MB

In [ ]:
customers.shape

(99441, 5)

In [ ]:
customers.isnull().sum()

customer_id                 0
customer_unique_id          0
customer_zip_code_prefix    0
customer_city               0
customer_state              0
dtype: int64

In [ ]:
customers.duplicated().sum()

np.int64(0)

-------  تنظيف وتوحيد نصوص أسماء المدن (إزالة المسافات الزائدة وتحويلها لحروف صغيرة)-------

In [ ]:
customers['customer_city'] = customers['customer_city'].astype(str).str.strip().str.lower()

------- تحويل الولايات لحروف كبيرة لتطابق تنسيق ملف الجيولكيشن بالظبط--------

In [ ]:
customers['customer_state'] = customers['customer_state'].astype(str).str.strip().str.upper()

------- الحفاظ على الـ Zip Code كـ Integer (رقم) ليطابق نوع بيانات ملف الجيولكيشن تماماً-------

In [ ]:
customers['customer_zip_code_prefix'] = customers['customer_zip_code_prefix'].astype(int)

---------فحص أبعاد الجدول والتحقق من أن معرف العميل فريد بالكامل--------

In [ ]:
print("Dataset Shape:", customers.shape)
print("Is customer_id fully unique?:", customers['customer_id'].nunique() == len(customers))

Dataset Shape: (99441, 5)
Is customer_id fully unique?: True

-------نحسب أولاً كم مرة اشترى كل عميل فريد------

In [ ]:
purchase_counts = customers['customer_unique_id'].value_counts()

--------نحدد العملاء الذين اشتروا أكثر من مرة-------

In [ ]:
repeat_customers = purchase_counts[purchase_counts > 1].count()

-------نحسب إجمالي عدد العملاء الفريدين-------

In [ ]:
total_unique_customers = customers['customer_unique_id'].nunique()

-----حساب النسبة المئوية-----

In [ ]:
repeat_rate = (repeat_customers / total_unique_customers) * 100

In [ ]:
customers.to_csv('cleaned_customers.csv', index=False)