<a href="https://colab.research.google.com/github/NadaMagdy-hub/Olist-E-Commerce-Data-Analysis/blob/main/orders.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
orders= pd.read_csv("/content/olist_orders_dataset.csv")

In [ ]:
orders.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00

In [ ]:
orders.tail()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
41335,d4b97a63d751219f528e5c3067341564,da432f82dd35cf00fb08da4a18150c82,delivered,2018-05-21 22:43:47,2018-05-22 02:15:40,2018-05-22 10:47:00,2018-06-12 23:03:53,2018-06-05 00:00:00
41336,b89b697cf1384ba59f3ce56bc8d28cc6,c5279c1aed890b6931837dda06d188c9,delivered,2018-08-09 20:25:37,2018-08-09 20:35:14,2018-08-10 15:29:00,2018-08-15 16:07:46,2018-08-22 00:00:00
41337,f0c8ddc6f3738f7bb122c0250983a494,dce677bd5ee1fdd44dd3dab91f9ab846,delivered,2017-10-27 14:36:33,2017-10-27 15:32:52,2017-10-30 13:23:34,2017-11-08 12:48:48,2017-11-10 00:00:00
41338,49e86652f7ea8a48b2306abdd5aa5708,37c117383b391157a1e253b395d73cee,delivered,2018-07-13 17:00:17,2018-07-13 17:30:35,2018-07-17 16:17:00,2018-07-23 17:58:47,2018-08-27 00:00:00
41339,fc6e4c97f5307e9c1bc0797a45e40cbf,b195b30a0c289a41ee810335d3c06364,delivered,2018-03-14 17:57:56,2018,NaN,NaN,NaN

In [ ]:
orders.columns.tolist()

['order_id',
 'customer_id',
 'order_status',
 'order_purchase_timestamp',
 'order_approved_at',
 'order_delivered_carrier_date',
 'order_delivered_customer_date',
 'order_estimated_delivery_date']

In [ ]:
orders.shape

(41340, 8)

In [ ]:
orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 41340 entries, 0 to 41339
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       41340 non-null  object
 1   customer_id                    41340 non-null  object
 2   order_status                   41340 non-null  object
 3   order_purchase_timestamp       41340 non-null  object
 4   order_approved_at              41264 non-null  object
 5   order_delivered_carrier_date   40611 non-null  object
 6   order_delivered_customer_date  40111 non-null  object
 7   order_estimated_delivery_date  41339 non-null  object
dtypes: object(8)
memory usage: 2.5+ MB

In [ ]:
orders.duplicated().sum()

np.int64(0)

In [ ]:
orders.isna().sum()

order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                  76
order_delivered_carrier_date      729
order_delivered_customer_date    1229
order_estimated_delivery_date       1
dtype: int64

In [ ]:
orders['order_status'].value_counts()

order_status
delivered      40112
shipped          473
canceled         259
unavailable      244
invoiced         125
processing       124
created            3
Name: count, dtype: int64

---------تحويل أعمدة التواريخ من نصوص إلى Datetime-----------

In [ ]:
date_columns = [
    'order_purchase_timestamp',
    'order_approved_at',
    'order_delivered_carrier_date',
    'order_delivered_customer_date',
    'order_estimated_delivery_date'
]

for col in date_columns:
    orders[col] = pd.to_datetime(orders[col], errors='coerce')

----------تنظيف النصوص وإزالة المسافات العشوائية---------

In [ ]:
orders['order_status'] = orders['order_status'].str.strip().str.lower()
orders['order_id'] = orders['order_id'].str.strip()
orders['customer_id'] = orders['customer_id'].str.strip()

-------- حذف الطلبات التي تم تعليمها كـ delivered ولكن ليس لها تاريخ توصيل فعلي (عددها 8 فقط)-------

In [ ]:
orders = orders.drop(orders[(orders['order_status'] == 'delivered') & (orders['order_delivered_customer_date'].isnull())].index)

------الكود ده بيعمل عمود جديد في جدول البيانات عشان يصنف الطلبات لـ "تم التوصيل" أو "لم يتم التوصيل" بناءً على حالة الطلب الحالية-----

In [ ]:
orders['delivery_status'] = orders['order_status'].apply(
    lambda x: 'Delivered' if x == 'delivered' else 'Not Delivered'
)

-------حسب لي بالظبط كم طلب طلع Delivered وكم طلب طلع Not Delivered-------

In [ ]:
orders['delivery_status'].value_counts()

delivery_status
Delivered        40109
Not Delivered     1228
Name: count, dtype: int64

------حساب الأيام المستغرقة للتوصيل الفعلي--------

In [ ]:
orders['delivery_time_days'] = (orders['order_delivered_customer_date'] - orders['order_purchase_timestamp']).dt.days

---------حساب الأيام المتوقعة للتوصيل (حسب النظام)-------

In [ ]:
orders['estimated_delivery_time_days'] = (orders['order_estimated_delivery_date'] - orders['order_purchase_timestamp']).dt.days

------حساب الفرق بين التوصيل الفعلي والمتوقع (إذا كان السعر بالسالب يعني التوصيل متأخر)------

In [ ]:
orders['delivery_delta_days'] = (orders['order_estimated_delivery_date'] - orders['order_delivered_customer_date']).dt.days

-----إضافة مؤشر هل الطلب متأخر أم لا؟------
--الرقم 1 لو الطلب اتأخر فعلاً، والرقم 0 لو الطلب وصل في ميعاده أو بدري--

In [ ]:
orders['is_late'] = np.where(orders['delivery_delta_days'] < 0, 1, 0)

In [ ]:
orders.isna().sum()

order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                  76
order_delivered_carrier_date      728
order_delivered_customer_date    1226
order_estimated_delivery_date       0
delivery_status                     0
delivery_time_days               1226
estimated_delivery_time_days        0
delivery_delta_days              1226
is_late                             0
dtype: int64

In [ ]:
orders.describe()

,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,delivery_time_days,estimated_delivery_time_days,delivery_delta_days,is_late
count,41337,41261,40609,40111,41337,40111.000000,41337.000000,40111.000000,41337.000000
mean,2017-12-31 15:14:22.148366080,2018-01-01 01:10:04.323986176,2018-01-05 05:27:47.198970880,2018-01-14 16:34:00.733240320,2018-01-24 08:18:31.952972032,12.038094,23.347679,10.884471,0.077243
min,2016-09-04 21:15:19,2016-09-15 12:16:38,2016-10-08 10:34:01,2016-10-11 14:46:49,2016-09-30 00:00:00,0.000000,2.000000,-182.000000,0.000000
25%,2017-09-13 08:03:54,2017-09-13 17:15:29,2017-09-18 20:07:04,2017-09-26 20:23:22,2017-10-04 00:00:00,6.000000,18.000000,6.000000,0.000000
50%,2018-01-18 18:39:15,2018-01-19 02:38:48,2018-01-24 01:09:36,2018-02-02 19:48:38,2018-02-15 00:00:00,10.000000,23.000000,11.000000,0.000000
75%,2018-05-04 16:04:30,2018-05-04 21:35:17,2018-05-08 13:31:00,2018-05-15 23:24:14,2018-05-28 00:00:00,15.000000,28.000000,16.000000,0.000000
max,2018-10-03 18:55:29,2018-08-29 14:31:07,2018-09-03 12:56:00,2018-10-17 13:22:46,2018-10-25 00:00:00,209.000000,149.000000,146.000000,1.000000
std,NaN,NaN,NaN,NaN,NaN,9.401578,8.839273,10.071862,0.266980

In [ ]:
orders.describe(include='object')

,order_id,customer_id,order_status,delivery_status
count,41337,41337,41337,41337
unique,41337,41337,7,2
top,49e86652f7ea8a48b2306abdd5aa5708,37c117383b391157a1e253b395d73cee,delivered,Delivered
freq,1,1,40109,40109

In [ ]:
orders.to_csv("cleaning_orders.csv", index=False)