<a href="https://colab.research.google.com/github/NadaMagdy-hub/Olist-E-Commerce-Data-Analysis/blob/NadaMagdy-hub-patch-1/translation_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import re

In [ ]:
translation = pd.read_csv("product_category_name_translation.csv")

In [ ]:
translation.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 71 entries, 0 to 70
Data columns (total 2 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   product_category_name          71 non-null     object
 1   product_category_name_english  71 non-null     object
dtypes: object(2)
memory usage: 1.2+ KB

In [ ]:
translation.head()

    product_category_name product_category_name_english
0            beleza_saude                 health_beauty
1  informatica_acessorios         computers_accessories
2              automotivo                          auto
3         cama_mesa_banho                bed_bath_table
4        moveis_decoracao               furniture_decor

In [ ]:
translation.tail()

            product_category_name product_category_name_english
66                         flores                       flowers
67             artes_e_artesanato         arts_and_craftmanship
68                fraldas_higiene           diapers_and_hygiene
69  fashion_roupa_infanto_juvenil     fashion_childrens_clothes
70             seguros_e_servicos         security_and_services

In [ ]:
translation.isnull().sum()

product_category_name            0
product_category_name_english    0
dtype: int64

In [ ]:
translation.duplicated().sum()

np.int64(0)

In [ ]:
translation.product_category_name.duplicated().sum()

np.int64(0)

------# 2. إزالة المسافات الزائدة وتحويل النصوص لحروف صغيرة (Lowercase) لتوحيد مفتاح الربط-------

In [ ]:
translation['product_category_name'] = translation['product_category_name'].astype(str).str.strip().str.lower()
translation['product_category_name_english'] = translation['product_category_name_english'].astype(str).str.strip().str.lower()

In [ ]:
translation.to_csv('cleaned_product_category_name_translation.csv', index=False)